#!/usr/bin/env -S bash
#  polyglot-env -*- mode: sh -*-

#set -o errexit
set -o nounset
set -o pipefail

# shellcheck disable=SC1091
source "$POLY_SRC/lib/lib.bash"

STUB_HEADER="# -- Polyglot Vars (remember to add 'export' as necessary)"
STUB_FOOTER="# -- End of Polyglot Vars"
PRINTED_HELP="${PRINTED_HELP:-2}"
HELP_TEXT="
usage: polyglot env [-s] [-h]

Print or Stub env vars for .envrc

options:
-h, --help    : show this help message and exit
-s, --stub    : print a set of stub env vars
"

maybe-print-help "branch" 0 "$HELP_TEXT" "$@"

# The simplest variables
STUB_TEXT="
export POLYGLOT_ROOT=\"\$PWD\"

export POLYGLOT_SRC=\"\$PWD/src\"
export POLYGLOT_DATA=\"\$PWD/src/_data\"

export POLYGLOT_TEMP=\"\$PWD/.temp\"
export POLYGLOT_LOGS=\"\$PWD/.temp/logs\"
export POLYGLOT_DOCS=\"\$PWD/.temp/docs\"

export POLYGLOT_DEFAULT_LANGS=\"python;rust\"
export POLYGLOT_DEFAULT_TOOLS=\"mdbook\"
export POLYGLOT_DEFAULT_TASKS=\"validate;sync;build;clean;docs;export;release\"
"

EXT_STUB_TEXT="${POLYGLOT_STUB_TEXT:-}"
EXT_STUB_FILE="${POLYGLOT_STUB_FILE:-}"

declare -a ARGS=(-e "POLYGLOT")
for val in "${POLYGLOT_ENV_PREFIXES[@]}"
do
    ARGS+=(-e "$val")
done

if [[ -f "${EXT_STUB_FILE}" ]]; then
    STUB_TEXT=$(< "${EXT_STUB_FILE}")
elif [[ -n "${EXT_STUB_TEXT}" ]]; then
    STUB_TEXT="${EXT_STUB_TEXT}"
fi

BODY=""
# Add polyglot vars to stub
BODY+=$(env | grep "POLYGLOT")
BODY+="${STUB_TEXT}"

for arg in "$@"
do
    BODY+=$(env | grep "$arg")
done

echo "${STUB_HEADER}"
echo "$BODY" | sort | uniq
echo ""
echo "${STUB_FOOTER}"

