#!/usr/bin/env -S bash
#  polyglot-add -*- mode: sh -*-

#set -o errexit
set -o nounset
set -o pipefail

# shellcheck disable=SC1091
source "$POLY_SRC/lib/lib-util.bash"

PRINTED_HELP="${PRINTED_HELP:-2}"
HELP_TEXT="
usage: polyglot add [-h] [type] [name]

Add a task/tool/lang template into .tasks,
using abbreviations set up in cookiecutterrc

positional arguments:
type : task|tool|lang|util
name : the template name

options:
-h, --help    : show this help message and exit

"

target="$POLYGLOT_ROOT/.temp/"

function add-ws-member () {
    local type="$1"
    local name="$2"
    local POLY_CTX="${POLY_CTX:-}"
    subhead "Adding $type: $name"
    POLY_CTX=$(pushctx "$name")

    polyglot check "$type" "$name" 2>/dev/null && tdot "add" "Member already added" && return
    tdot "add" "Target: $target"

    [[ ! -d "$target/_slug" ]] || rm -rf "$target/_slug"

    ( cookiecutter \
      --no-input \
      --output-dir "$target" \
      "$type:$name" \
      proj_name=$(basename "$POLYGLOT_ROOT")
      _slug="_slug"
    ) || fail "Failed to create $type $name"

    [[ -d "$target/_slug" ]] || fail "Could not find the slug to integrate"

    tdot "merge" "Integrating slug with workspace"
    rsync --append --archive "$target/_slug/"* "$POLYGLOT_ROOT"
    rsync --append --archive "$target/_slug/".* "$POLYGLOT_ROOT"

    case "$type" in
        tool|lang)
            polyglot check "$type" "$name" init || return 0
            polyglot "$type" "$name" init || fail "Failed to initialise $type $name"
            ;;
        task) ;;
    esac

    tdot "cleanup" "removing slug"
    # rm -rf "$target/_slug"
}

maybe-print-help "branch" 2 "$HELP_TEXT" "$@"
type="$1"
name="$2"

[[ -d "$POLYGLOT_ROOT/.tasks" ]] || fail "Tasks directory does not exist"


case "$type" in
    tool|lang|task) add-ws-member "$type" "$name" ;;
    util)           add-ws-member "util" "$name" ;;
    *) fail "Bad type. It should be one of [tool, task, lang, util]" ;;
esac


