#!/usr/bin/env bash
# polyglot-list.bash -*- mode: sh -*-
#set -o errexit
set -o nounset
set -o pipefail

source "$POLY_SRC/lib/lib-util.bash"

PRINTED_HELP="${PRINTED_HELP:-2}"
HELP_TEXT="
usage: polyglot list [-h] [arg]

List available tasks, languages, and tools.

positional arguments:
arg          : t|tasks l|langs o|tools

options:
-h, --help    : show this help message and exit

"

maybe-print-help "branch" 1 "$HELP_TEXT" "$@"

TARGET=""
case "${1:-}" in
    tasks|t)
        TARGET="task-"
        ;;
    langs|l)
        TARGET="lang-"
        ;;
    tools|o)
        TARGET="tool-"
        ;;
    templates)
        fail "TODO"
        ;;
    *)
        echo "Unknown target"
        exit 1
        ;;
esac

echo -e "Polyglot Registered ${TARGET/-/}s:"
base=$(realpath "$POLYGLOT_ROOT/.tasks")
for targ in $(find "$base" -maxdepth 1 -name "${TARGET}*" | sort -V)
do
    name=$(basename "$targ")
    echo "- ${name/$TARGET/}"
done
