#!/usr/bin/env bash
# polyglot-task -*- mode: sh -*-
#set -o errexit
set -o nounset
set -o pipefail

# shellcheck disable=SC1091
source "$POLY_SRC/lib/lib.bash"

HELP_TEXT="
usage: polyglot task [-l] [-hook=int] [target] [-h]

Use a registered task.

positional arguments:
target

options:
-h, --help    : show this help message and exit
-l, --list    : list the hooks of the target
-d, --dry     : dry-run the hooks.
--hook=int    : run just the nth hook of the target

"

# Maybe print cmd help
maybe-print-help "branch" 1 "$HELP_TEXT" "$@"

DO_DRY=0
NTH_HOOK=""
TASK_ARGS=()
TARGET=""
while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -l|--list)
            echo "Registered Tasks: "
            poly-list "task" "$TARGET" "- "
            exit
            ;;
        -d|--dry)
            DO_DRY=1
            ;;
        --hook=*)
            IFS="=" read -ra KEYVAL <<< "$1"
            NTH_HOOK="${KEYVAL[1]}"
            ;;
        *) # Positional
            if [[ -z "$TARGET" ]]; then
                TARGET="$1"
            else
                TASK_ARGS+=("$1")
            fi
            ;;
    esac
    shift
done

subhead "Task $TARGET"

if [[ -n "${NTH_HOOK:-}" ]]; then
    run-task-nth-hook "${NTH_HOOK}" "$TARGET" "${TASK_ARGS[@]}"
else
    run-task "$DO_DRY" "$TARGET" "${TASK_ARGS[@]}"
fi

