#!/usr/bin/env -S bash
#  polyglot-new -*- mode: sh -*-

#set -o errexit
set -o nounset
set -o pipefail

# shellcheck disable=SC1091
source "$POLY_SRC/lib/lib-util.bash"

PRINTED_HELP="${PRINTED_HELP:-2}"
HELP_TEXT="
usage: polyglot new [-h]

Shortcut to create a new polyglot workspace.
(using a cookiecutter abbreviation of 'polyglot')

positional arguments:

options:
-h, --help    : show this help message and exit

"

print-help "$HELP_TEXT" 0 "$@"

[[ "${#@}" -gt 0 ]] || fail "Provide a name for the project"
proj_name="$1"

[[ -d "$PWD/${proj_name}" ]] && fail "Workspace already exists: ${proj_name}"

header "Creating Workspace: $proj_name"
POLY_CTX=$(pushctx "new")

cookiecutter --no-input polyglot proj_name="$proj_name"
[[ -d "$PWD/${proj_name}" ]] || fail "Failed to create project"
pushd "${proj_name}" >/dev/null || fail "Failed to enter new project for initalisation"

POLY_CTX=$(pushctx "workspace")
pctx "Setting up workspace"

tdot "git" "Initialising git"
git init >/dev/null
git add --all 2>/dev/null
git commit -m "[initial]: workspace creation" 2>/dev/null >/dev/null

tdot "direnv" "Activating directory environment"
direnv allow
POLY_CTX="$POLY_CTX" direnv exec . polyglot task init     || fail "Failed to initialise"
POLY_CTX="$POLY_CTX" direnv exec . polyglot task validate || fail "Failed to validate"
popd >/dev/null || fail "Failed to enter new project"
