#!/usr/bin/env bash
# polyglot-task -*- mode: sh -*-
#set -o errexit
set -o nounset
set -o pipefail

source "$POLY_SRC/lib/lib-util.bash"
source "$POLY_SRC/lib/lib-hooks.bash"

header "polyglot task"

function print-help () {
    case "${@: 1}" in
        -h|--help) ;;
        *) if [[ "$#" -gt 0 ]]; then
               return
           fi
           ;;
    esac
    echo -e "
Call a specific registered task.

"
    exit 2
}

print-help "$@"
run-task "$POLYGLOT_ROOT/.tasks" "task-" "$@"
