#!/usr/bin/env bash
#  polyglot-lang -*- mode: sh -*-
#set -o errexit
set -o nounset
set -o pipefail

# shellcheck disable=SC1091
source "$POLY_SRC/lib/lib-util.bash"

PRINTED_HELP="${PRINTED_HELP:-2}"
HELP_TEXT="
usage: polyglot lang [-h] [-l] [langname subcmd]

Use a registered language's subcommand.

positional arguments:
langname
subcmd

options:
-h, --help     :  show this help message and exit
-l, --list     :  list the available subcmds of the language

"

function run-subcmd () {
    # run-subcmd {basedir} {subcmd} {args}
    # task is of the form lang-{sub} or lang-{sub}
    local base="$1"
    local prefix="$2"
    local lang="$3"
    local target="$4"
    shift 4
    [[ -n "$target" ]] || fail "No Applicable language subcommand specified"
    debug "- Checking for subcommand ${prefix}-$lang: $target"
    [[ -d "$base/${prefix}-${lang}" ]] || fail "No Applicable lang Found: ${lang}"

    subcmd-run "$base/${prefix}-${lang}" "$target"
    return "$?"
}

print-help "$HELP_TEXT" 0 "$@"

TARGET_LANG=""
SUBCMD=""
LANG_ARGS=()
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -l|--list)
            list-entries "$POLYGLOT_ROOT/.tasks" "lang" "$TARGET_LANG"
            exit
            ;;
        *) # Positional
            if [[ -z "$TARGET_LANG" ]]; then
                TARGET_LANG="$1"
            elif [[ -z "$SUBCMD" ]]; then
                SUBCMD="$1"
                shift
                LANG_ARGS=("${@}")
                break
            fi
            ;;
    esac
    shift
done

subhead "Lang: $TARGET_LANG.$SUBCMD :(${#LANG_ARGS[@]}) ${LANG_ARGS[*]}"

run-subcmd "$POLYGLOT_ROOT/.tasks" "lang" "$TARGET_LANG" "$SUBCMD" "${LANG_ARGS[@]}"
