#!/usr/bin/env bash
#  polyglot-release -*- mode: sh -*-


header "Running $LEVEL Release"

subhead "Checking for change notifications"
# one arg: the level of the version to bump
local LEVEL="${1:-minor}"
local CURR_VERSION
local NEW_VERSION
if [[ -n $(git --no-pager diff) ]]; then
    fail "There are unstaged changes."
fi
if [[ -n "$TOWNCRIER_CHANGE_DIR" ]]; then
    [[ -n $(fdfind . "$TOWNCRIER_CHANGE_DIR") ]] || fail "There are no fragment changes. Add descriptions of this release."
else
    towncrier check || fail "There are no fragment changes. Add descriptions of this release."
fi

run_version
run_towncrier
polyglot-export

git add --all
git commit -m "[Release]: ${NEW_VERSION}"
git tag "${NEW_VERSION}"
