#!/usr/bin/env bash
#  polyglot-lang -*- mode: sh -*-
#set -o errexit
set -o nounset
set -o pipefail

# shellcheck disable=SC1091
source "$POLY_SRC/lib/lib.bash"

PRINTED_HELP="${PRINTED_HELP:-2}"
HELP_TEXT="
usage: polyglot lang [-h] [-l] [langname subcmd]

Use a registered language's subcommand.

positional arguments:
langname
subcmd

options:
-h, --help     :  show this help message and exit
-l, --list     :  list the available subcmds of the language

"

maybe-print-help "branch" 2 "$HELP_TEXT" "$@"

TARGET_LANG=""
SUBCMD=""
LANG_ARGS=()
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -l|--list)
            echo "Registered Languages: "
            poly-list "lang" "$TARGET_LANG" "- "
            exit
            ;;
        *) # Positional
            if [[ -z "$TARGET_LANG" ]]; then
                TARGET_LANG="$1"
            elif [[ -z "$SUBCMD" ]]; then
                SUBCMD="$1"
                shift
                LANG_ARGS=("${@}")
                break
            fi
            ;;
    esac
    shift
done

subhead "Lang: $TARGET_LANG.$SUBCMD :(${#LANG_ARGS[@]}) ${LANG_ARGS[*]}"
run-lang-subcmd "$TARGET_LANG" "$SUBCMD" "${LANG_ARGS[@]}"
