#!/usr/bin/env -S bash
#  polyglot-env -*- mode: sh -*-

#set -o errexit
set -o nounset
set -o pipefail

# shellcheck disable=SC1091
source "$POLY_SRC/lib/lib-util.bash"

PRINTED_HELP="${PRINTED_HELP:-2}"
HELP_TEXT="
usage: polyglot env [-s] [-h]

Print or Stub the env vars for .envrc

options:
-h, --help    : show this help message and exit
-s, --stub    : print a set of stub env vars
"

maybe-print-help "branch" 0 "$HELP_TEXT" "$@"

STUB_TEXT="
# -- Core Polyglot Environment Variables for .envrc
export POLYGLOT_ROOT=\"\$PWD\"

export POLYGLOT_SRC=\"\$PWD/src\"
export POLYGLOT_DATA=\"\$PWD/src/_data\"

export POLYGLOT_TEMP=\"\$PWD/.temp\"
export POLYGLOT_LOGS=\"\$PWD/.temp/logs\"
export POLYGLOT_DOCS=\"\$PWD/.temp/docs\"

export POLYGLOT_DEFAULT_LANGS=\"python;rust\"
export POLYGLOT_DEFAULT_TOOLS=\"mdbook\"
export POLYGLOT_DEFAULT_TASKS=\"validate;sync;build;clean;docs;export;release\"
# --
"

declare -a ARGS=(-e "POLYGLOT")
for val in "${POLYGLOT_ENV_PREFIXES[@]}"
do
    ARGS+=(-e "$val")
done

# Print the stub:
while [[ $# -gt 0 ]]; do
    case $1 in
        -s|--stub)
            echo -e "$STUB_TEXT"
            exit 0
            ;;
        *)
            ARGS+=(-e "$1")
            ;;
    esac
    shift
done

# Or,
env | grep "${ARGS[@]}" | sort
