#!/usr/bin/env bash
# polyglot-stub.bash -*- mode: sh -*-
#set -o errexit
set -o nounset
set -o pipefail

# shellcheck disable=SC1091
source "$POLY_SRC/lib/lib-util.bash"

function print-help () {
    case "${@: 1}" in
        -h|--help) ;;
        *) if [[ "$#" -gt 0 ]]; then
               return
           fi
           ;;
    esac
    echo -e "usage: polyglot stub [-h] [type]

A utility to easily stub:
- task hooks,
- language cmds,
- tool cmds
- envrc additions

positional arguments:
type : [hook, help, lang, tool, envrc]

options:
-h, --help    : show this help message and exit

"
    exit "$PRINTED_HELP"
}

function print-task-hook-stub () {
    # shellcheck disable=SC2016
    echo -e '#!/usr/bin/env bash
# Stub shell script for a task hook.
# Place in $root/.tasks/task-{name}/[0-9].{desc}.bash
# then make it executable with chmod +x
set -o nounset
set -o pipefail

# shellcheck disable=SC1091
source "$POLY_SRC/lib/lib-util.bash"

fname=$(basename "${BASH_SOURCE[0]}")
header "($HOOK_NUM): $fname.\n* Args: " "$@"

# Parse args:
while [[ $# -gt 0 ]]; do
    case $1 in
        -t|--target)
            echo "Target: $2"
            ;;
        --bloo=*)
            echo "Assignment: $1"
            IFS="=" read -ra KEYVAL <<< "$1"
            echo "Key: ${KEYVAL[0]/--/}"
            echo "Val: ${KEYVAL[1]}"
            ;;
        *) # Positional
            echo "Positional: $1"
            ;;
    esac
    shift
done

echo "TODO: hook implementation"

# Return Codes:
# - 0 : success
# - 1 : failure
# - 2 : help printed
'
}

function print-hook-help-stub () {
    # shellcheck disable=SC2016
    echo -e '#!/usr/bin/env bash
# place in $root/.tasks/task-{name}/0.help.bash
# and chmod +x it.
set -o nounset
set -o pipefail

# shellcheck disable=SC1091
source "$POLY_SRC/lib/lib-util.bash"

case "${@: -1}" in
    -h|--help)
    # hook help:

    exit "$PRINTED_HELP" ;;
    *) ;;
esac
'
}

function print-lang-cmd-stub () {
    # shellcheck disable=SC2016
    echo -e '#!/usr/bin/env bash
# A Stub language command.
# Place in $root/.tasks/lang-{name}/{cmd}.bash
# and chmod +x it.
set -o nounset
set -o pipefail

# shellcheck disable=SC1091
source "$POLY_SRC/lib/lib-util.bash"

echo "TODO: language command."
'
}

function print-tool-cmd-stub () {
    # shellcheck disable=SC2016
    echo -e '#!/usr/bin/env bash
# A Stub tool command.
# Place in $root/.tasks/tool-{name}/{cmd}.bash
# and chmod +x it.
set -o nounset
set -o pipefail

# shellcheck disable=SC1091
source "$POLY_SRC/lib/lib-util.bash"

echo "TODO: tool command."
'
}

function print-envrc-stub () {
    # shellcheck disable=SC2016
    echo '# -- Standard Polyglot Environment Variables for .envrc

# For adding task-local utilities:
# export PYTHONPATH="$PWD/.tasks:$PYTHONPATH"

# The root of the project:
export POLYGLOT_ROOT="$PWD"

# Where package sources are located:
export POLYGLOT_SRC="src"

# A directory to build temporary files, able to be deleted without worry:
export POLYGLOT_TEMP=".temp"

# Sphinx documentation:
export POLYGLOT_SPHINX_BUILDER="html"
export POLYGLOT_SPHINX_CONF_DIR="$POLYGLOT_SRC/_sphinx"
export POLYGLOT_USE_BIBTEX=1
# --'
}

print-help "$@"

case $1 in
    hook) print-task-hook-stub ;;
    help) print-hook-help-stub ;;
    lang) print-lang-cmd-stub  ;;
    tool) print-tool-cmd-stub  ;;
    envrc) print-envrc-stub    ;;
    *) fail "No stub target type provided" ;;
esac
