#!/usr/bin/env bash
# polyglot-tool -*- mode: sh -*-
# set -o errexit
set -o nounset
set -o pipefail

# shellcheck disable=SC1091
source "$POLY_SRC/lib/lib.bash"

PRINTED_HELP="${PRINTED_HELP:-2}"
HELP_TEXT="
usage: polyglot tool [-h] [-l] [toolname subcmd]

Use a registered tool's subcommand.

positional arguments:
toolname
subcmd

options:
-h, --help     :  show this help message and exit
-l, --list     :  list the available subcmds of the tool

"

maybe-print-help "branch" 2 "$HELP_TEXT" "$@"
TOOL=""
SUBCMD=""
TOOL_ARGS=()
while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -l|--list)
            echo "Registered Tools: "
            poly-list "tool" "$TOOL" "- "
            exit
            ;;
        *) # Positional
            if [[ -z "$TOOL" ]]; then
                TOOL="$1"
            elif [[ -z "$SUBCMD" ]]; then
                SUBCMD="$1"
                shift
                TOOL_ARGS=("${@}")
                break
            fi
            ;;
    esac
    shift
done

subhead "Tool: $TOOL.$SUBCMD :(${#TOOL_ARGS[@]}) ${TOOL_ARGS[*]}"
run-tool-subcmd "$TOOL" "$SUBCMD" "${TOOL_ARGS[@]}"
