#!/usr/bin/env -S bash
#  polyglot-new -*- mode: sh -*-

#set -o errexit
set -o nounset
set -o pipefail

# shellcheck disable=SC1091
source "$POLY_SRC/lib/lib-util.bash"

function print-help () {
    # test args, if the last one is -h or --help
    # print help and exit
    case "${@: -1}" in
        -h|--help) ;;
        *) if [[ "$#" -gt 0 ]]; then
               return
           fi
           ;;
    esac
    echo -e "
usage: polyglot new [-h]

Shortcut to create a new polyglot workspace.
(using a cookiecutter abbreviation of 'polyglot')

positional arguments:

options:
-h, --help    : show this help message and exit


"
    exit "${PRINTED_HELP:-2}"
}

function verbose-result () {
    if [[ "${VERBOSE:-0}" -eq 0 ]]; then
       exit "$1"
    fi

    if [[ "$1" -eq 0 ]]; then
        echo "$target is loaded"
    else
        echo "$target is not loaded"
    fi
    exit "$1"
}

print-help "$@"

cookiecutter polyglot
