#!/usr/bin/env -S bash
#  polyglot-check -*- mode: sh -*-

#set -o errexit
set -o nounset
set -o pipefail

# shellcheck disable=SC1091
source "$POLY_SRC/lib/lib.bash"

PRINTED_HELP="${PRINTED_HELP:-2}"
HELP_TEXT="
usage: polyglot check [-h] [type] [arg]

Checks that a task, tool, or lang component exists in POLYGLOT_DIR.

eg: polyglot check task release

positional arguments:
type   : task/tool/lang
name   : name of the component to check for.

options:
-h, --help    : show this help message and exit

"

maybe-print-help "branch" 1 "$HELP_TEXT" "$@"

type="$1"
target="$2"
subtarget="${3:-}"

case "$type" in
    tool|task|lang) ;;
    *) fail "Unrecognised check type: $type"
esac

joined="${type}-${target}"
path="$(poly-dir)/${joined}"

# Check for general existance
[[ -d "$path" ]] || exit 1

# If a specific part is provided, check for it
[[ -n "$subtarget" ]] || exit 0

subcmd-exists-check "$path" "$subtarget"
