#!/usr/bin/env -S bash
#  polyglot-check -*- mode: sh -*-

#set -o errexit
set -o nounset
set -o pipefail

# shellcheck disable=SC1091
source "$POLY_SRC/lib/lib-util.bash"

PRINTED_HELP="${PRINTED_HELP:-2}"
HELP_TEXT="
usage: polyglot check [-h] [arg]

Checks that a task-arg, tool-arg, or lang-arg exists in .tasks

positional arguments:
arg          : full name of task/tool/lang to test is loaded

options:
-h, --help    : show this help message and exit

"

function print-help () {
    # test args, if the last one is -h or --help
    # print help and exit
    case "${@: -1}" in
        -h|--help) ;;
        *) if [[ "$#" -gt 0 ]]; then
               return
           fi
           ;;
    esac
    echo -e "${HELP_TEXT}"
    exit "$PRINTED_HELP"
}

print-help "$@"

type="$1"
target="$2"
subtarget="${3:-}"

case "$type" in
    tool|task|lang) ;;
    *) fail "Unrecognised check type: $type"
esac

joined="${type}-${target}"
path="${POLYGLOT_ROOT}/.tasks/${joined}"

# Check for general existance
[[ -d "$path" ]] || exit 1

# If a specific part is provided, check for it
[[ -n "$subtarget" ]] || exit 0

subcmd-exists-check "$path" "$subtarget"
