#!/usr/bin/env bash
#  polyglot-list -*- mode: sh -*-


echo "# -- Polyglot Environment Variables for .envrc
export POLYGLOT_ROOT=\"\$PWD\"
export POLYGLOT_SRC=\"src\"
export POLYGLOT_TEMP=\".temp\"
export POLYGLOT_SPHINX_BUILDER=\"html\"
export POLYGLOT_SPHINX_CONF_DIR=\"\$POLYGLOT_SRC/_sphinx\"
export POLYGLOT_USE_BIBTEX=1
# --"
