#!/usr/bin/env bash
# polyglot-tool -*- mode: sh -*-
# set -o errexit
set -o nounset
set -o pipefail

# shellcheck disable=SC1091
source "$POLY_SRC/lib/lib-util.bash"

PRINTED_HELP="${PRINTED_HELP:-2}"
HELP_TEXT="
usage: polyglot tool [-h] [-l] [toolname subcmd]

Use a registered tool's subcommand.

positional arguments:
toolname
subcmd

options:
-h, --help     :  show this help message and exit
-l, --list     :  list the available subcmds of the tool

"

function run-tool-subcmd () {
    # run-tool-subcmd {basedir} {subcmd} {args}
    # task is of the form lang-{sub} or tool-{sub}
    local base="$1"
    local prefix="$2"
    local tool="$3"
    local target="$4"
    shift 4
    [[ -d "$base/${prefix}-${tool}" ]] || fail "No Applicable Tool Found: ${tool}"

    subcmd-run "$base/${prefix}-${tool}" "${target}"
    return "$?"
}

maybe-print-help "branch" 2 "$HELP_TEXT" "$@"
TOOL=""
SUBCMD=""
TOOL_ARGS=()
while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -l|--list)
            list-entries "$POLYGLOT_ROOT/.tasks" "tool" "$TOOL"
            exit
            ;;
        *) # Positional
            if [[ -z "$TOOL" ]]; then
                TOOL="$1"
            elif [[ -z "$SUBCMD" ]]; then
                SUBCMD="$1"
                shift
                TOOL_ARGS=("${@}")
                break
            fi
            ;;
    esac
    shift
done

subhead "Tool: $TOOL.$SUBCMD :(${#TOOL_ARGS[@]}) ${TOOL_ARGS[*]}"
run-tool-subcmd "$POLYGLOT_ROOT/.tasks" "tool" "$TOOL" "$SUBCMD" "${TOOL_ARGS[@]}"
