#!/usr/bin/env bash
# polyglot -*- mode: sh -*-
# Main script for polyglot projects, to hook into cargo.
# polyglot is aliased as 'pg_' in places
#set -o errexit
set -o nounset
set -o pipefail

POLYGLOT_VERSION="0.3.0"

current_script_path=$(realpath "${BASH_SOURCE[0]}")
POLY_SRC=$(realpath "$(dirname "$current_script_path")")

PATH="$POLY_SRC/cmds:$PATH"
# shellcheck disable=SC1091
source "$POLY_SRC/lib/lib-util.bash"

function run-free-cmds () {
    # early override for when you aren't in a workspace,
    # and want one.
    print-version "$@"
    local cmdname="$1"
    shift
    case "$cmdname" in
        new)
            # shellcheck disable=SC2097,SC2098
            POLY_SRC="$POLY_SRC" polyglot-new "$@"
            exit "$?" ;;
        env)
            POLY_SRC="$POLY_SRC" polyglot-env "$@"
            exit "$?" ;;
        -h|--help|help)
            POLY_SRC="$POLY_SRC" polyglot-help "$@"
            exit "$?"
            ;;
        *) ;;
    esac
}

function print-version () {
    case "${@: -1}" in
        -v|--version) echo "$POLYGLOT_VERSION" && exit 0 ;;
    esac
}

# General
VERBOSE=${VERBOSE:-0}


case "${POLYGLOT_ROOT:-}" in
    "") # Not in a workspace
        run-free-cmds "$@"
        fail "(Polyglot $POLYGLOT_VERSION): Make sure theres a POLYGLOT_ROOT env var, or run 'polyglot new'"
    ;;
    *) # In a workspace
        print-version "$@"
        cmd_base="${1:-help}"
        shift
        case "$cmd_base" in
            -h|--help|-help|help) cmd="polyglot-help" ;;
            *) cmd="polyglot-${cmd_base}" ;;
        esac

        POLY_SRC="$POLY_SRC" "$cmd" "$@"
        result="$?"
        case "$result" in
            "${PRINTED_HELP}" | 0) exit 0;;
            *) exit "$result" ;;
        esac
    ;;
esac
