#!/usr/bin/env bash
# polyglot -*- mode: sh -*-
# Main script for polyglot projects, to hook into cargo.
# polyglot is aliased as 'pg_' in places
#set -o errexit
set -o nounset
set -o pipefail

POLYGLOT_VERSION="0.2.0"

current_script_path=$(realpath "${BASH_SOURCE[0]}")
POLY_SRC=$(realpath "$(dirname "$current_script_path")")

# shellcheck disable=SC1090
source "$POLY_SRC/lib/lib-util.bash"
source "$POLY_SRC/lib/lib-hooks.bash"

if [[ "$1" = "new" ]]; then
    # early override for when you aren't in a workspace,
    # and want one.
    run-cmd "$POLY_SRC/cmds" "polyglot-" "$@"
    exit "$?"
fi

if [[ -z "$POLYGLOT_ROOT" ]]; then
    # if you think you're in a workspace, but aren't.
    echo "(Polyglot $POLYGLOT_VERSION): Make sure theres a POLYGLOT_ROOT env var"
    exit 1
fi

# General
VERBOSE=${VERBOSE:-0}

if [[ "${1:-}" = "polyglot" ]]; then
    shift
fi
is-help-flag "${1:-}"
is_help="$?"
if [[ "$#" -eq 0 ]] || [[ "$is_help" -gt 0 ]]; then
    # print help if you just call polyglot
    # shellcheck disable=SC2098,SC2097
    POLY_SRC="$POLY_SRC" "$POLY_SRC/cmds/polyglot-help"
    exit 0
fi

case "${@: -1}" in
    -v|--version)
        echo "$POLYGLOT_VERSION"
        exit 0
    ;;
esac

# Polyglot Internal:
# polyglot {cmd}
run-cmd "$POLY_SRC/cmds" "polyglot-" "$@"
result="$?"
if [[ "$result" -ne "$NOTHING" ]]; then
    exit "$result"
fi

fail "No Applicable Command or task found."
